{% set version = '1.3.3.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mcr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/mcr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/mcr/mcr_{{ version }}.tar.gz
  sha256: 29fbf13990fe5eb7edc5ab9c61c37c0824c87b708ab5e655f417bf8af4b2773d

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ stdlib("c") }}            # [not win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-robslopes
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-robslopes
    ## NB: win gcc-libgfortran dep likely needs manual removal in UCRT migration
    - {{ native }}gcc-libgfortran  # [win]

test:
  commands:
    - $R -e "library('mcr')"           # [not win]
    - "\"%R%\" -e \"library('mcr')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mcr
  license: GPL-3.0-or-later
  summary: Regression methods to quantify the relation between two measurement methods are provided
    by this package. In particular it addresses regression problems with errors in both
    variables and without repeated measurements. It implements the CLSI recommendations
    (see J. A. Budd et al. (2018, <https://clsi.org/standards/products/method-evaluation/documents/ep09/>)
    for analytical method comparison and bias estimation using patient samples. Furthermore,
    algorithms for Theil-Sen and equivariant Passing-Bablok estimators are implemented,
    see F. Dufey (2020, <doi:10.1515/ijb-2019-0157>) and J. Raymaekers and F. Dufey
    (2022, <arXiv:2202:08060>). A comprehensive overview over the implemented methods
    and references can be found in the manual pages "mcr-package" and "mcreg".
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
